node {
   // This is to demo github action
   stage('SCM Checkout'){
    // Clone repo
	git branch: 'master',
	credentialsId: 'github',
	url: 'https://github.com/chandresh-nova/aws-sample-app.git'

   }


   stage('Mvn Package'){
	   // Build using maven
       def mvnHome = tool (name: 'maven', type: 'maven') + '/bin/mvn'
	   sh "${mvnHome} clean package deploy"
   }

}