node {
   // This is to demo github action
   stage('SCM Checkout'){
    // Clone repo
	git branch: 'master',
	credentialsId: 'github',
	url: 'https://github.com/chandresh-nova/aws-sample-app.git'

   }

    stage('Build') {
            **dir('project-dir') {**
                sh 'mvn clean install'
                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
            }
        }

}