apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: simple
          image: skaffold-simple
          ports:
            - containerPort: 9090