apiVersion: v1
kind: Service
metadata:
  name: simple
  labels:
    name: simple
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: simple
  type: LoadBalancer